In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [30]:
a = np.array([1, 2, 3]) # 1d array
b = np.array([[1, 2, 3], [4, 5, 6]]) # 2d array
#-------------------------------------------------

z = np.zeros((2, 3))
ones = np.ones((3, 3))

# ------------------------------------------------
identity = np.eye(3)
ar = np.arange(0, 10, 2)
lin = np.linspace(0, 1, 6)
# ------------------------------------------------

#print(a)
#print(b)
#print(z)
#print(ones)
print(identity)
print(ar)
print(lin) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8 1. ]


In [31]:
# Numpy Attributes
#-----------------
print(b)
print(b.shape) # returns number of ROWS & COLS
print(b.ndim)  # returns number of DIMENSION
print(b.size)  # returns the product of rows & cols
print(b.dtype) # returns the exact datatype of values stored in numpy arrays

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int32


In [14]:
print(b)
#print(b[0, 1])
#print(b[:, 2])  # if slicinng starts with : followed by a num then it returns entire num column values 
#print(b[1, :]) # if slicing starts with num ffolloweed by : then it returns entire num row values
print(b[0:2, 0:2])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [37]:
#print(ar)  # [0 2 4 6 8]  # (1,5)
#reshaped = ar.reshape(5, 1)
#print(reshaped)
#print(ar)
#print(b)
#flat = b.flatten() # flatten converts any array into 1d array temporarily
#print(flat)
print(b)

raveled = b.ravel()
print(raveled)
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [38]:
x = np.array([1, 2, 3]) # 1d
y = np.array([4, 5, 6]) # 1d

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [39]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

print(matrix + vector)

[[11 22 33]
 [14 25 36]]


In [42]:
#print(matrix.sum())
#print(matrix.mean())
#print(np.median(matrix))
#print(matrix.std())
#print(matrix.var())
#print(matrix.min())
#print(matrix.max())
print(matrix)
#print(matrix.sum(axis=0))
#print(matrix.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[ 6 15]


In [44]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print(np.dot(m1, m2)) # row * column - split multiplication using dot matrix * 
print(m1 @ m2) # here @ represents DOT MATRIX MULTIPLICATION
#print(m1)
#print(m1.T)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [49]:
#np.random.seed(42)

#print(np.random.rand(2, 3)) # finger print authentication 
#print(np.random.randint(100, 210, size=(2, 3))) # otp 
print(np.random.randn(2, 3))

[[ 2.11050284  0.52801052 -0.03321567]
 [-0.69371863 -0.5178737  -0.26649174]]


In [53]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

#print(np.vstack((v1, v2)))
#print(np.hstack((v1, v2)))
#print(np.concatenate((v1, v2)))
print(np.split(np.arange(9), 3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [56]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])

#print(np.sort(unsorted))
#print(np.argsort(unsorted)) # used in  gen ai along with SLM
#print(np.where(unsorted > 3)) # conditional sorting

(array([2, 4, 5, 7], dtype=int64),)


In [57]:
data = np.array([10, 15, 20, 25, 30])
mask = data > 18

print(mask)
print(data[mask])

[False False  True  True  True]
[20 25 30]


In [ ]:
np.save('array_data.npy', data)
loaded = np.load('array_data.npy')

print(loaded)