In [1]:
import numpy as np

In [2]:
arr=np.array([
    [4,5,7],
    [7,8,6]
])
print(arr)

[[4 5 7]
 [7 8 6]]


In [8]:
#slicing
print(arr[0,1])
print(arr[:,0])#if slicing starts with : followed by a num then it returns entire num column values
print(arr[0, :])# if slicing starts with num ffolloweed by : then it returns entire num row values

5
[4 7]
[4 5 7]


In [11]:
marks = np.array([[24,45,67,89],

                 [56,78,90,78],

                 [67,78,96,65],

                 [45,78,98,67]])
print(marks[:3]) 
print(marks[:,2]) #row
print(marks[:,3])

[[24 45 67 89]
 [56 78 90 78]
 [67 78 96 65]]
[67 90 96 98]
[89 78 65 67]


In [14]:
#reshaping
temperature = np.array([

    25, 26, 27, 28,

    29, 30, 31, 32,

    33, 34, 35, 36

])

temperature = temperature.reshape(3, 4)

tempe = temperature.flatten()

temp = temperature.ravel()


print(temperature)
print(tempe)
print(temp)

[[25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]
[25 26 27 28 29 30 31 32 33 34 35 36]
[25 26 27 28 29 30 31 32 33 34 35 36]


In [16]:
#Arithmetic operations
x = np.array([1, 2, 3]) # 1d

y = np.array([4, 5, 6]) # 1d

print(x + y)

print(x - y)

print(x * y)

print(x / y)

print(x ** 2)
print(np.add(x,y))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[5 7 9]


In [19]:
#bradcasting
marks1 = np.array([

    [80, 70, 90],

    [60, 85, 75]

])

bonus = np.array([5,10,5])

print(marks1 + bonus)

[[85 80 95]
 [65 95 80]]


In [25]:
#Aggregation
matrix = np.array([

    [80, 70, 90],

    [60, 85, 75]

])
print(matrix.sum())
print(matrix.mean())
print(np.median(matrix))
print(matrix.std())
print(matrix.var())
print(matrix.min())
print(matrix.max())
print(matrix)
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

460
76.66666666666667
77.5
9.860132971832694
97.22222222222223
60
90
[[80 70 90]
 [60 85 75]]
[140 155 165]
[240 220]


In [26]:
#Dot product
# NumPy also supports linear algebra operations including the dot product, matrix multiplication, transposition, matrix inversion, and the determinant of a matrix.

m1 = np.array([[1, 2], [3, 4]])

m2 = np.array([[5, 6], [7, 8]])


print(np.dot(m1, m2)) # row * column - split multiplication using dot matrix * 

print(m1 @ m2) # here @ represents DOT MATRIX MULTIPLICATION

#print(m1)

#print(m1.T)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [27]:
#sorting
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])


print(np.sort(unsorted))
print(np.where(unsorted > 3)) # conditional sorting

[1 1 2 3 4 5 6 9]
[1 3 6 0 2 4 7 5]
(array([2, 4, 5, 7]),)


In [28]:
# Boolean indexing makes it possible to filter an array based on a condition, returning only the elements that meet the criteria.

data = np.array([10, 15, 20, 25, 30])

mask = data > 18

print(mask)

print(data[mask])

[False False  True  True  True]
[20 25 30]
